AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Project pi be less
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UserAPI
      StageName: Prod
      Description: API for FE user requests
      Cors:
        AllowMethods: "'POST, GET, DELETE, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ##### Hello world lambda #####
  HelloWorldLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/helloWorld.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Hello world lambda'
      MemorySize: 128
      Timeout: 30
      Events:
        HelloWorldLambdaEvent:
          Type: Api
          Properties:
            Path: /helloWorld
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  ##### Questions API lambdas really #####
  DeleteQuestionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/question/deleteQuestion.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        DeleteQuestionLambdaEvent:
          Type: Api
          Properties:
            Path: /question/{id}/{questionId}
            Method: delete
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  PostQuestionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/question/postQuestion.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /question/{id}/{questionId}
            Method: post
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  ShowQuestionLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/question/showQuestion.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /question/{id}/{questionId}
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  GetQuestionnaireQuestionsLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/question/getQuestionnaireQuestions.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /question/{id}
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  ##### Questionnaire API lambdas #####
  deleteQuestionnaireLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/questionnaire/deleteQuestionnaire.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /questionnaire/{id}
            Method: delete
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  getQuestionnaireLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/questionnaire/getQuestionnaire.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /questionnaire
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  postQuestionnaireLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/questionnaire/postQuestionnaire.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /questionnaire/{id}
            Method: post
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  showQuestionnaireLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/questionnaire/showQuestionnaire.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /questionnaire/{id}
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  ##### Types API lambdas #####
  getQuestionTypeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/types/getQuestionType.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /question-type
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"
  getAlgorithmTypeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/types/getAlgorithmType.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Description: 'Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::258885766453:role/LambdaDynamoDBRole'
      Events:
        deleteQuestionAPI:
          Type: Api
          Properties:
            Path: /algorithm-type
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          REGION: "eu-west-1"